"""Add scanner models

Revision ID: 21a8ae4a45bb
Revises: e6916b0e64e7
Create Date: 2026-09-07 19:09:19.820648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21a8ae4a45bb'
down_revision: Union[str, Sequence[str], None] = 'e6916b0e64e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_images',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('scan_id', sa.String(length=32), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('alt_text', sa.Text(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scan_links',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('scan_id', sa.String(length=32), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_external', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scan_pages',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('scan_id', sa.String(length=32), nullable=False),
    sa.Column('requested_url', sa.Text(), nullable=False),
    sa.Column('final_url', sa.Text(), nullable=False),
    sa.Column('page_title', sa.Text(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.Text(), nullable=True),
    sa.Column('viewport', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('html', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_id')
    )
    op.create_table('scan_performance',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('scan_id', sa.String(length=32), nullable=False),
    sa.Column('navigation_start', sa.Float(), nullable=True),
    sa.Column('dom_content_loaded', sa.Float(), nullable=True),
    sa.Column('load_event', sa.Float(), nullable=True),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_id')
    )
    op.create_table('scan_requests',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('scan_id', sa.String(length=32), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scan_screenshots',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('scan_id', sa.String(length=32), nullable=False),
    sa.Column('image_data', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_id')
    )
    op.create_table('scan_scripts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('scan_id', sa.String(length=32), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('is_inline', sa.Boolean(), nullable=False),
    sa.Column('script_type', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scan_stylesheets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('scan_id', sa.String(length=32), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('is_inline', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scan_stylesheets')
    op.drop_table('scan_scripts')
    op.drop_table('scan_screenshots')
    op.drop_table('scan_requests')
    op.drop_table('scan_performance')
    op.drop_table('scan_pages')
    op.drop_table('scan_links')
    op.drop_table('scan_images')
    # ### end Alembic commands ###
